### PR TITLE
[COOK-3820] Fixed deprecated includes

### PR DESCRIPTION
**Pull request by jregeimbal**
Cleaning up my runs, wanted to contribute fixes for these warnings:
"Chef::Mixin::LanguageIncludeRecipe is deprecated, use Chef::DSL::IncludeRecipe"

https://tickets.opscode.com/browse/COOK-3820

### CODE REVIEW

**Comment by sethvargo** [comment]
@jregeimbal ohai! I thank you for your contribution. Have you signed the CLA? I do not see you in the JIRA developers group.

**Comment by jregeimbal** [comment]
Hi Seth,

I signed the CLA about an hour ago and confirmed my email address, let me
know if there is anything else I need to do.

Thanks,

Jonathan

On Tue, Oct 15, 2013 at 2:38 PM, Seth Vargo notifications@github.comwrote:

> @jregeimbal https://github.com/jregeimbal ohai! I thank you for your
> contribution. Have you signed the CLA? I do not see you in the JIRA
> developers group.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/opscode-cookbooks/application_php/pull/10#issuecomment-26360700
> .

## 

Jonathan Regeimbal
v: 540.907.5116
e: jonathan@regeimbal.net

**Comment by sethvargo** [comment]
@jregeimbal awesome. Thank you so much for doing that and contributing to Opscode cookbooks. We are in the works to improve the process, but in the meantime it's a manual one. Can you check back in a day and see if you have been added to the JIRA developers group? You'll know because you'll see a "Fix Provided" button at the top of your JIRA ticket in the ticketing system.

**Comment by jregeimbal** [comment]
@sethvargo of course, I like what you guys have put together with Chef, very powerful stuff.  I'll take a look tomorrow and let you know.

**Comment by sethvargo** [comment]
For reference, you're looking for this button:

__cook-3820__fixed_deprecated_includes_-_opscode_open_source_ticket_tracking

**Comment by jregeimbal** [comment]
Hi Seth,

I was contacted by a Shauna Chernicoff to notify me that I am an approved
developer and have been added to the Jira developer group.  However, the
changes do not seem to have taken affect yet.  Going to give it a day and
contact Shauna if there is no movement.

Thanks,
Jonathan

**Comment by jregeimbal** [comment]
Hi Seth,

I've been added to the JIRA developers group, and am seeing the "Fix
Provided" button now.

Thanks,
Jonathan

**Comment by arangamani** [comment]
@sethvargo @coderanger What is the status on this? Can we merge this one?

**Comment by coderanger** [comment]
Thanks for the patch!

**Pull request merged**
